# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169Ddxe2c4_MsjWRanNS4muQVZXeRABBY

# ***SIMPLE LINEAR REGRESSION***

**IMPORTING THE LIBRARIES**
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""**IMPORTING THE DATASET**"""

data= pd.read_csv('train.csv')
data=data.dropna(how='any')
x= data.iloc[:,:-1].values
y= data.iloc[:,-1].values
data

print(x)

y=y.reshape(len(y),1)
print(y)

"""**SPLITTING THE DATA**"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/4,random_state=1)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

"""# **Training the Simple Linear Regression model**"""

from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(x_train,y_train)

"""**VISUALISING SET RESULTS**

TRAINING SET
"""

plt.scatter(x_train,y_train,color='yellow')
plt.plot(x_train,LR.predict(x_train),color='cyan')
plt.title('Salary vs Experience(TRAINING SET')
plt.xlabel("YEARS OF EXPERIENCE")
plt.ylabel('SALARY')
plt.show()

"""TEST SET"""

plt.scatter(x_test,y_test,color='yellow')
plt.plot(x_train,LR.predict(x_train),color='cyan')
plt.title('Salary vs Experience(TEST SET')
plt.xlabel("YEARS OF EXPERIENCE")
plt.ylabel('SALARY')
plt.show()

"""**Prediciting the test results**"""

y_pred=LR.predict(x_test)
print(y_pred)

"""**ACCURACY TEST**"""

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(regressor.coef_)
print(regressor.intercept_)

from sklearn.metrics import r2_score
a=r2_score(y_test, y_pred)
print(abs(a*100))

print(LR.predict([[51]]))

print(LR.coef_)
print(LR.intercept_)